In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import re 
import string
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
from pylab import *
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_patio_lawn_garden = pd.read_json\
('https://raw.githubusercontent.com/PacktWorkshops/The-Natural-Language-Processing-Workshop/master/Chapter03/data/reviews_Patio_Lawn_and_Garden_5.json',
                          lines=True)
data_patio_lawn_garden[['reviewText', 'overall']].head()

                                          reviewText  overall
0  Good USA company that stands behind their prod...        4
1  This is a high quality 8 ply hose. I have had ...        5
2  It's probably one of the best hoses I've ever ...        4
3  I probably should have bought something a bit ...        5
4  I bought three of these 5/8-inch Flexogen hose...        5

In [3]:
lemmatizer = WordNetLemmatizer()
data_patio_lawn_garden['cleaned_review_text'] = data_patio_lawn_garden['reviewText'].\
apply(lambda x: ' '.join([lemmatizer.lemmatize(word.lower())\
for word in word_tokenize(re.sub(r'([^\s\w]|_)+', ' ', str(x)))]))
data_patio_lawn_garden[['cleaned_review_text', 'reviewText', 'overall']].head()

,cleaned_review_text,reviewText,overall
0,good usa company that stand behind their produ...,Good USA company that stands behind their prod...,4
1,this is a high quality 8 ply hose i have had g...,This is a high quality 8 ply hose. I have had ...,5
2,it s probably one of the best hose i ve ever h...,It's probably one of the best hoses I've ever ...,4
3,i probably should have bought something a bit ...,I probably should have bought something a bit ...,5
4,i bought three of these 5 8 inch flexogen hose...,I bought three of these 5/8-inch Flexogen hose...,5

In [4]:
tfidf_model = TfidfVectorizer(max_features=500)
tfidf_df = pd.DataFrame(tfidf_model.\
                        fit_transform(data_patio_lawn_garden['cleaned_review_text']).\
                        todense())
tfidf_df.columns = sorted(tfidf_model.vocabulary_)
tfidf_df.head()

,10,20,34,8217,able,about,actually,add,after,again,...,work,worked,working,worth,would,yard,year,yet,you,your
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.120568,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.161561,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.116566,0.0,0.216988,0.000000,0.049357
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.064347,0.0,0.0,0.070857,0.0,...,0.0,0.0,0.0,0.0,0.0,0.083019,0.0,0.000000,0.000000,0.000000

In [5]:
data_patio_lawn_garden['target'] = data_patio_lawn_garden['overall'].\
apply(lambda x: 0 if x <= 4 else 1)
data_patio_lawn_garden['target'].value_counts()

1    7037
0    6235
Name: target, dtype: int64

In [6]:
def clf_model(model_type, X_train, y):
    model = model_type.fit(X_train, y)
    predicted_labels = model.predict(tfidf_df)
    return predicted_labels

# XGBoost

In [ ]:
conda install -c conda-forge xgboost

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |

In [ ]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(n_estimators=20, learning_rate=0.03,
                        max_depth=5, subsample=0.6, colsample_bytree=0.6,
                        reg_alpha=10, seed=42)                            
data_patio_lawn_garden['predicted_labels_xgbc'] = clf_model(xgb_clf, tfidf_df,
                                                          data_patio_lawn_garden['target'])
pd.crosstab(data_patio_lawn_garden['target'], data_patio_lawn_garden['predicted_labels_xgbc'])

In [ ]:
def reg_model(model_type, X_train, y):
    model = model_type.fit(X_train, y)
    predicted_labels = model.predict(tfidf_df)
    return predicted_labels

In [ ]:
from xgboost import XGBRegressor
xgbr = XGBRegressor(n_estimators=20, learning_rate=0.03,
                        max_depth=5, subsample=0.6, colsample_bytree=0.6,
                        reg_alpha=10, seed=42)
data_patio_lawn_garden['predicted_labels_xgbr'] = reg_model\
(xgbr, tfidf_df, data_patio_lawn_garden['overall'])
data_patio_lawn_garden[['overall', 'predicted_labels_xgrb']].head(2)